# Generated by Django 3.1.7 on 2021-04-09 14:48

import datetime
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210408_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 9), validators=[main.validators.validate_age]),
        ),
    ]
