# Generated by Django 3.1.7 on 2021-04-09 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210409_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 9)),
        ),
    ]
